### ISSUE TITLE
Nothing listed under PvP filters

### ISSUE THREAD

**Issue by Nick2bad4u** [andreasx23/GuildSpamFilter#2]
No settings under PvP filters:

![image](https://user-images.githubusercontent.com/20943337/218216703-5f88d643-9508-44c8-9753-6324a72f9f19.png)

**Comment by andreasx23** [comment]
Hi sir,
Thank you for posting regarding this. Luckily this will be in the next version of Clan Spam Filter! Already in [Pull Request](https://github.com/runelite/plugin-hub/pull/3852)

![Clan Spam Filter update](https://user-images.githubusercontent.com/49310598/218246711-8811a1d5-50ae-4c51-87f0-cf13ac8e063b.png)

**Comment by Nick2bad4u** [comment]
Thank you!
