### ISSUE TITLE
Always allow self option doesn't work

### ISSUE THREAD

**Issue by TrevorMDev** [andreasx23/GuildSpamFilter#3]
The check for Always allow self seems to be backwards. When checked, the messages for yourself are filtered, and when unchecked allows them through.

**Comment by andreasx23** [comment]
Hi!
Thank you for reporting this issue, I will have a look at it tonight :-)

**Comment by andreasx23** [comment]
Sorry that it took me awhile, but a fix for this issue has been sent to PR (https://github.com/runelite/plugin-hub/pull/4992)
