### ISSUE TITLE
Filters don't seem to be working properly?

### ISSUE THREAD

**Issue by SandroVA** [andreasx23/GuildSpamFilter#4]
Filter Raid Drops - True
Raid Loot GP Threshold - 5,000,000

But items like dex doesn't appear. This is just one example but I feel like other things are also getting filtered.

**Comment by andreasx23** [comment]
> Filter Raid Drops - True Raid Loot GP Threshold - 5,000,000
> 
> But items like dex doesn't appear. This is just one example but I feel like other things are also getting filtered.

Thank you for letting me know about this, I will take a look into it :-)

**Comment by andreasx23** [comment]
A pull request with a fix for this issue has been sent to RuneLite: https://github.com/runelite/plugin-hub/pull/5920
