### ISSUE TITLE
Combat Achievements filter not working?

### ISSUE THREAD

**Issue by Dyna1One** [andreasx23/GuildSpamFilter#5]
Hi there, I'm not sure if I'm doing anything wrong but the combat achievements are still popping up for me (I have it turned on and set to all)

**Comment by andreasx23** [comment]
> Hi there, I'm not sure if I'm doing anything wrong but the combat achievements are still popping up for me (I have it turned on and set to all)


Hi!
Thank you for the report, I will take a look into the issue :-)

**Comment by Dyna1One** [comment]
Thank you! Amazing plugin by the way, besides this little error it's exactly what I was looking for!
