### ISSUE TITLE
Leagues filter

### ISSUE THREAD

**Issue by CodePanter** [andreasx23/GuildSpamFilter#6]
Hello! I was hoping you might be able to include some way to filter out leagues broadcast from the clan chat. I'd totally understand if you can't make it fully customizable; but honestly a 'full leagues broadcast' filter would be amazing; as I'm expecting the gains to keep coming for weeks 😆

**Comment by NathanCollaert** [comment]
Added a leagues broadcast filter to the plugin. PR #7 just needs approval and merge fron he creator.

**Comment by andreasx23** [comment]
> Added a leagues broadcast filter to the plugin. PR #7 just needs approval and merge fron he creator.

Approved the pull request. We just need to submit to for review at RuneLite now.
Edit: I have submitted the PR: https://github.com/runelite/plugin-hub/pull/7088

**Comment by andreasx23** [comment]
> Hello! I was hoping you might be able to include some way to filter out leagues broadcast from the clan chat. I'd totally understand if you can't make it fully customizable; but honestly a 'full leagues broadcast' filter would be amazing; as I'm expecting the gains to keep coming for weeks 😆

It is currently possible to filter the broadcasts using the "Custom filter" section. Just type some of the texts e.g. "relic" and everything containing relic will be removed. Further broadcasts can be filtered by using comma seperation

**Comment by andreasx23** [comment]
This feature is now live on RuneLite. Update your plugin by restarting your client and it can be found in the Miscellaneous tab :-)
